### ISSUE TITLE
Unknown names for some files

### ISSUE THREAD

**Issue by endervad** [divergentdave/tomestone-utils#12]
After using `discover_paths` command on a clean game (which produced a 127Mb database) the names for some files were not acquired. I see in README that currently about 1/3 of all file name can be recovered but I hope creating this issue won't hurt anyway.

I also noticed that in `exd` pack some of the files have two names. They are as follows:
```
PS C:\Users\dev\Desktop\repos\tomestone-utils\target\release> .\tomestone-dump.exe list exd | Select-String '\['

exd/transport/["u5f2_a4_obj02_d.tex", "aetherytelakeland.exh"]
exd/quest/037/["s1d2_p1_moss1_s.tex", "fesnyr701_03738_0_de.exd"]
exd/cut_scene/041/["d2f2_l2_obj18.pcb", "voiceman_04101_0_ja.exd"]
exd/custom/005/["pic_ta_20207a_d.tex", "cmndefretainermarketregister_00581_0_ja.exd"]
```
Here are the lists that I got. I sorted them via `Sort-Object` in PowerShell.
[common-list.txt](https://github.com/divergentdave/tomestone-utils/files/8215838/common-list.txt)
[exd-list.txt](https://github.com/divergentdave/tomestone-utils/files/8215840/exd-list.txt)

**Comment by divergentdave** [comment]
Yes, generally speaking I'm not aspiring to get 100% coverage on file names. I'm open to suggestions for new heuristics to add to `discover_paths`. I think I'm pretty happy with coverage in the exd pack, as exd/root.exl identifies all but a handful of files, and the remainder could well be unused in the game.

Regarding the ambiguous output from the list command, I have an idea to fix that by cross-referencing between the two different index files. The reason for showing multiple names presently is that the sheer number of files across all the packs results in some collisions of CRC-32 checksums for different halves of file paths. Since we typically have two sets of indexes for the same files, using different CRC-32 schemes, we could try each possibility we see from `.index` in `index2`, and filter down to one result. (I currently prefer using `.index` here, because even if the full path isn't known I can often show the folder component if that's known already)

**Comment by endervad** [comment]
I see, thanks for the answer. Aside from `exd` pack I'm personally also interested in `common` pack since it has font files which ideally my team need to edit. So then I'll try to figure this out in my free time.

**Comment by divergentdave** [comment]
Looking at the strings of ffxiv_dx11.exe, I found `common/font/fontIcon_Xinput.tex` and `common/font/gfdata.gfd`. Note that the `hex` and `raw` subcommands can't yet dump the .tex file, as I don't have support written for how texture or model files are compressed. There are also some format strings for `common/font/font%d.tex` and `common/font/font_lobby%d.tex`, which together give me a dozen other filenames. Having found those, I now see there are about a hundred other files in the same subdirectory, but I don't have leads on those at the moment.

**Comment by divergentdave** [comment]
The improvement to the list command is done, closing this issue for now.
